[balance_new_me_encrypted_1]
x = "0x034ed15cc9c368232e3926503d285e05f1ebed691e83dd928ca96c9ef0ce7368"
y = "0x0967e26ca6d6476a92fdf6e3417219351a51c337fb0a43fcfedc50f3009c036f"

[balance_new_me_encrypted_2]
x = "0x0fc4b44aaef6456b6ab9903eca0611ae93c698e83e34d83a61420999df6cc08a"
y = "0x2dcaf1254efb6c12adae349d535daf925a7d3d8a7e7f07aeebdcec95989ea3d6"

[balance_new_to_encrypted_1]
x = "0x1b3b24fd014e645f74ad11ccec3ab063eb5eb7da09c8f268067c9414294c71ab"
y = "0x1393df002387b6175fd1a926e4e258b46247f12a9a6aa722f4f3ccec2704d33a"

[balance_new_to_encrypted_2]
x = "0x1d95d1e74c2947a3e4b738470a97938b19d9f5a69a171d0ee13d31a2791c2df3"
y = "0x16492aefb5c8ef737e3200b35f5a5c8433c88c73aadc0aa282b0a10e9155a16f"

[balance_old_me_encrypted_1]
x = "0x185bf7468d377d2c4ed1029c0b8a63b1c60b1c29b2294998d86b9e22632a0d91"
y = "0x01f8647518c40d31bb502f15e6335c926d17dda7415fcff8b745b35a4129ac0d"

[balance_old_to_encrypted_1]
x = "0x0b366dafa211192fe80411271803da623a36d6a454b50b6ab185787bc8cda1ef"
y = "0x27fff44b6051ec18a8d8ff6e49522e20978ea5e58ce2d580ba8451f25fdc9c97"

[balance_old_to_encrypted_2]
x = "0x026485697e83e94495e3c025604ff322260f92e96743b5b99e5934b8b890f778"
y = "0x00dbf8007d3364db4acead4665c835c48f7c6eb44c033fe5c9c953629d9fcf86"

[public_key_me]
x = "0x1865e98a61eb14dd9366fbc6808c3cd93aec7cf0adcecd86711c17e8e96cf95a"
y = "0x2a6b15f46f69a6a6f8991466900b57585a49e31643cc04b0070f6d74db9f9fdc"

[public_key_to]
x = "0x0a3ee6a5015696854620bb5584968102e80d745d5a25466eb4d6767a6ef1beb0"
y = "0x22a6b0ac121d1d668544bc2258107a9e714976581f247ea3050b9d304556551e"
